//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottishParliamentMembers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int PersonID { get; set; }
        public string PhotoURL { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool BirthDateIsProtected { get; set; }
        public string ParliamentaryName { get; set; }
        public string PreferredName { get; set; }
        public int GenderTypeID { get; set; }
        public bool IsActive { get; set; }
    }
}
